"""
BigQuery-backed store for CDS study data.

All study output collections (study_alerts, study_sbar_import, study_task_import,
study_suppressed_events, study_metrics_snapshots, pipeline_run_costs) are stored
in the `cds_study` dataset in BigQuery.

Tables are created automatically on first use via CREATE TABLE IF NOT EXISTS DDL.

Auth: Workload Identity / Application Default Credentials — no key file needed
      when running on Cloud Run with the correct runtime service account.
      Locally: set GOOGLE_APPLICATION_CREDENTIALS or use
                gcloud auth application-default login.
"""
from __future__ import annotations

import json
import logging
import os
import uuid
from datetime import datetime, timezone
from typing import Any

from google.cloud import bigquery

log = logging.getLogger(__name__)

_PROJECT = "prod-tech-project1-bv479-zo027"
_DATASET = "cds_study"
_LOCATION = "asia-south1"


# ── helpers ───────────────────────────────────────────────────────────────────

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _dt_to_iso(v) -> str | None:
    if v is None:
        return None
    if isinstance(v, datetime):
        if v.tzinfo is None:
            v = v.replace(tzinfo=timezone.utc)
        return v.isoformat()
    return str(v)


def _to_json_col(v) -> str | None:
    if v is None:
        return None
    if isinstance(v, str):
        return v
    try:
        return json.dumps(v, default=str)
    except Exception:
        return str(v)


def _new_id() -> str:
    return str(uuid.uuid4())


# ── DDL ───────────────────────────────────────────────────────────────────────

_DDL: dict[str, str] = {}

_DDL["study_alerts"] = f"""
CREATE TABLE IF NOT EXISTS `{_PROJECT}.{_DATASET}.study_alerts` (
  alert_id               STRING    NOT NULL,
  CPMRN                  STRING,
  encounter              INT64,
  problem_name           STRING,
  alert_reason           STRING,
  alerted_at             TIMESTAMP,
  match_status           STRING,
  matched_sbar_id        STRING,
  matched_task_id        STRING,
  llm_match_confidence   FLOAT64,
  llm_match_reasoning    STRING,
  fp_candidate_at        TIMESTAMP,
  adjudicated_at         TIMESTAMP,
  created_at             TIMESTAMP
)
OPTIONS (description = "CDS system alerts generated by problem_tracker")
"""

_DDL["study_sbar_import"] = f"""
CREATE TABLE IF NOT EXISTS `{_PROJECT}.{_DATASET}.study_sbar_import` (
  sbar_id               STRING    NOT NULL,
  CPMRN                 STRING,
  encounter             INT64,
  hospital_name         STRING,
  unit_name             STRING,
  urgency               STRING,
  issues                STRING,
  module                STRING,
  create_date_time      TIMESTAMP,
  is_reviewed           BOOL,
  reviewer_name         STRING,
  action                STRING,
  window_expires_at     TIMESTAMP,
  match_status          STRING,
  matched_alert_id      STRING,
  llm_match_confidence  FLOAT64,
  llm_match_reasoning   STRING,
  matched_at            TIMESTAMP,
  confirmed_fn_at       TIMESTAMP,
  excluded_at           TIMESTAMP,
  exclusion_reason      STRING,
  dedup_reason          STRING,
  fn_verdict            STRING,
  fn_excusal_reason     STRING,
  fn_reviewer_notes     STRING,
  fn_adjudicated_at     TIMESTAMP,
  synced_at             TIMESTAMP
)
OPTIONS (description = "SBARs synced from BigQuery patient tables")
"""

_DDL["study_task_import"] = f"""
CREATE TABLE IF NOT EXISTS `{_PROJECT}.{_DATASET}.study_task_import` (
  task_id               STRING    NOT NULL,
  CPMRN                 STRING,
  encounter             INT64,
  hospital_name         STRING,
  unit_name             STRING,
  title                 STRING,
  issues                STRING,
  priority              STRING,
  status                STRING,
  task_visible_at       TIMESTAMP,
  window_expires_at     TIMESTAMP,
  match_status          STRING,
  matched_alert_id      STRING,
  llm_match_confidence  FLOAT64,
  llm_match_reasoning   STRING,
  matched_at            TIMESTAMP,
  confirmed_fn_at       TIMESTAMP,
  excluded_at           TIMESTAMP,
  exclusion_reason      STRING,
  dedup_reason          STRING,
  deduplicated_at       TIMESTAMP,
  fn_verdict            STRING,
  fn_excusal_reason     STRING,
  fn_reviewer_notes     STRING,
  fn_adjudicated_at     TIMESTAMP,
  synced_at             TIMESTAMP
)
OPTIONS (description = "Review Abnormal Vitals tasks synced from BigQuery")
"""

_DDL["study_suppressed_events"] = f"""
CREATE TABLE IF NOT EXISTS `{_PROJECT}.{_DATASET}.study_suppressed_events` (
  CPMRN               STRING,
  encounter           INT64,
  problem_name        STRING,
  suppressed_at       TIMESTAMP,
  suppression_reason  STRING,
  created_at          TIMESTAMP
)
OPTIONS (description = "Alert events suppressed by cooldown logic")
"""

_DDL["study_metrics_snapshots"] = f"""
CREATE TABLE IF NOT EXISTS `{_PROJECT}.{_DATASET}.study_metrics_snapshots` (
  computed_at              TIMESTAMP,
  tp                       INT64,
  fp                       INT64,
  fn                       INT64,
  fn_sbar                  INT64,
  fn_task                  INT64,
  tn                       INT64,
  total_patient_hours      INT64,
  sensitivity              FLOAT64,
  specificity              FLOAT64,
  ppv                      FLOAT64,
  npv                      FLOAT64,
  f1                       FLOAT64,
  sensitivity_ci           STRING,
  specificity_ci           STRING,
  ppv_ci                   STRING,
  lead_time_median_minutes FLOAT64,
  lead_time_iqr_minutes    FLOAT64,
  lead_time_n              INT64,
  suppressed_total         INT64,
  suppressed_with_sbar     INT64,
  pending_adjudication     INT64,
  adj_total                INT64,
  adj_appropriate          INT64,
  adj_inappropriate        INT64,
  expl_clear               INT64,
  expl_partial             INT64,
  expl_unclear             INT64,
  alerts_total             INT64,
  sbars_total              INT64,
  tasks_total              INT64,
  excluded_downtime        INT64,
  task_excluded_downtime   INT64,
  task_deduplicated        INT64
)
OPTIONS (description = "Hourly study metrics snapshots")
"""

_DDL["pipeline_run_costs"] = f"""
CREATE TABLE IF NOT EXISTS `{_PROJECT}.{_DATASET}.pipeline_run_costs` (
  run_started_at   TIMESTAMP,
  computed_at      TIMESTAMP,
  patient_count    INT64,
  trace_count      INT64,
  model            STRING,
  totals           STRING,
  by_step          STRING,
  pricing          STRING
)
OPTIONS (description = "Per-run LLM token costs")
"""

_DDL["study_adjudications"] = f"""
CREATE TABLE IF NOT EXISTS `{_PROJECT}.{_DATASET}.study_adjudications` (
  alert_id              STRING,
  verdict               STRING,
  explainability_rating INT64,
  reviewer_notes        STRING,
  reviewed_at           TIMESTAMP
)
OPTIONS (description = "Manual adjudications from review UI")
"""

_DDL["fn_adjudications"] = f"""
CREATE TABLE IF NOT EXISTS `{_PROJECT}.{_DATASET}.fn_adjudications` (
  record_id        STRING,
  source           STRING,
  verdict          STRING,
  new_status       STRING,
  excusal_reason   STRING,
  reviewer_notes   STRING,
  adjudicated_at   TIMESTAMP,
  CPMRN            STRING,
  encounter        INT64
)
OPTIONS (description = "FN adjudications from review UI")
"""


# ── BQStudyStore ──────────────────────────────────────────────────────────────

class BQStudyStore:
    """
    Provides typed read/write methods for all study collections in BigQuery.

    Usage:
        store = get_bq_store()
        store.insert_alert({...})
        rows = store.find_alerts({"match_status": "pending", ...})
        store.update_alert_status(alert_id, "matched", matched_sbar_id="...")
    """

    def __init__(self, project: str = _PROJECT, dataset: str = _DATASET):
        self._project = project
        self._dataset = dataset
        self._client  = bigquery.Client(project=project)
        self._tables_ensured: set[str] = set()

    def _fqn(self, table: str) -> str:
        return f"`{self._project}.{self._dataset}.{table}`"

    def _ensure_table(self, table: str):
        if table in self._tables_ensured:
            return
        ddl = _DDL.get(table)
        if not ddl:
            log.warning("bq_store: no DDL for table %s — skipping ensure", table)
            return
        try:
            self._client.query(ddl).result()
            log.info("bq_store: ensured table %s.%s", self._dataset, table)
            self._tables_ensured.add(table)
        except Exception:
            log.exception("bq_store: failed to ensure table %s", table)

    def _query(self, sql: str, params: list | None = None) -> list[dict]:
        """Execute a SELECT and return rows as list of dicts."""
        job_config = bigquery.QueryJobConfig(query_parameters=params or [])
        try:
            rows = self._client.query(sql, job_config=job_config).result()
            return [dict(row) for row in rows]
        except Exception:
            log.exception("bq_store: query failed\n%s", sql)
            return []

    def _execute(self, sql: str, params: list | None = None) -> int:
        """Execute a DML (INSERT/UPDATE/MERGE) and return affected row count."""
        job_config = bigquery.QueryJobConfig(query_parameters=params or [])
        try:
            job = self._client.query(sql, job_config=job_config)
            job.result()
            return job.num_dml_affected_rows or 0
        except Exception:
            log.exception("bq_store: DML failed\n%s", sql)
            return 0

    # ── study_alerts ──────────────────────────────────────────────────────────

    def insert_alert(self, doc: dict) -> str:
        """Insert a new alert row. Returns the generated alert_id."""
        self._ensure_table("study_alerts")
        alert_id = doc.get("alert_id") or _new_id()
        sql = f"""
        INSERT INTO {self._fqn("study_alerts")}
          (alert_id, CPMRN, encounter, problem_name, alert_reason,
           alerted_at, match_status, created_at)
        VALUES
          (@alert_id, @CPMRN, @encounter, @problem_name, @alert_reason,
           @alerted_at, @match_status, @created_at)
        """
        self._execute(sql, [
            bigquery.ScalarQueryParameter("alert_id",     "STRING",    alert_id),
            bigquery.ScalarQueryParameter("CPMRN",        "STRING",    doc.get("CPMRN", "")),
            bigquery.ScalarQueryParameter("encounter",    "INT64",     doc.get("encounter", 1)),
            bigquery.ScalarQueryParameter("problem_name", "STRING",    doc.get("problem_name", "")),
            bigquery.ScalarQueryParameter("alert_reason", "STRING",    doc.get("alert_reason", "")),
            bigquery.ScalarQueryParameter("alerted_at",   "TIMESTAMP", _dt_to_iso(doc.get("alerted_at"))),
            bigquery.ScalarQueryParameter("match_status", "STRING",    doc.get("match_status", "pending")),
            bigquery.ScalarQueryParameter("created_at",   "TIMESTAMP", _now_iso()),
        ])
        return alert_id

    def update_alert(self, alert_id: str, fields: dict):
        """Update arbitrary fields on an alert by alert_id."""
        self._ensure_table("study_alerts")
        if not fields:
            return
        set_clauses = []
        params = [bigquery.ScalarQueryParameter("alert_id", "STRING", alert_id)]
        for k, v in fields.items():
            param_name = f"p_{k}"
            if isinstance(v, datetime):
                params.append(bigquery.ScalarQueryParameter(param_name, "TIMESTAMP", _dt_to_iso(v)))
            elif isinstance(v, float):
                params.append(bigquery.ScalarQueryParameter(param_name, "FLOAT64", v))
            elif isinstance(v, int):
                params.append(bigquery.ScalarQueryParameter(param_name, "INT64", v))
            else:
                params.append(bigquery.ScalarQueryParameter(param_name, "STRING", str(v) if v is not None else None))
            set_clauses.append(f"{k} = @{param_name}")
        sql = f"""
        UPDATE {self._fqn("study_alerts")}
        SET {', '.join(set_clauses)}
        WHERE alert_id = @alert_id
        """
        self._execute(sql, params)

    def bulk_update_alerts(self, filter_sql: str, set_sql: str, params: list):
        """Generic UPDATE with caller-provided WHERE and SET fragments."""
        self._ensure_table("study_alerts")
        sql = f"""
        UPDATE {self._fqn("study_alerts")}
        SET {set_sql}
        WHERE {filter_sql}
        """
        return self._execute(sql, params)

    def find_alerts(self, filter: dict) -> list[dict]:
        """SELECT alerts matching filter dict (CPMRN, encounter, match_status, alerted_at range)."""
        self._ensure_table("study_alerts")
        clauses, params = _build_where("study_alerts", filter)
        where = " AND ".join(clauses) if clauses else "TRUE"
        sql = f"SELECT * FROM {self._fqn('study_alerts')} WHERE {where}"
        return self._query(sql, params)

    def count_alerts(self, filter: dict) -> int:
        self._ensure_table("study_alerts")
        clauses, params = _build_where("study_alerts", filter)
        where = " AND ".join(clauses) if clauses else "TRUE"
        sql = f"SELECT COUNT(*) AS n FROM {self._fqn('study_alerts')} WHERE {where}"
        rows = self._query(sql, params)
        return rows[0]["n"] if rows else 0

    # ── study_sbar_import ─────────────────────────────────────────────────────

    def upsert_sbar(self, doc: dict) -> bool:
        """MERGE-upsert a SBAR row. Returns True if this was a new row."""
        self._ensure_table("study_sbar_import")
        sql = f"""
        MERGE {self._fqn("study_sbar_import")} T
        USING (SELECT @sbar_id AS sbar_id) S
        ON T.sbar_id = S.sbar_id
        WHEN NOT MATCHED THEN INSERT (
          sbar_id, CPMRN, encounter, hospital_name, unit_name, urgency, issues, module,
          create_date_time, is_reviewed, reviewer_name, action, window_expires_at,
          match_status, matched_alert_id, synced_at
        ) VALUES (
          @sbar_id, @CPMRN, @encounter, @hospital_name, @unit_name, @urgency, @issues, @module,
          @create_date_time, @is_reviewed, @reviewer_name, @action, @window_expires_at,
          @match_status, NULL, @synced_at
        )
        """
        n = self._execute(sql, [
            bigquery.ScalarQueryParameter("sbar_id",          "STRING",    doc["sbar_id"]),
            bigquery.ScalarQueryParameter("CPMRN",            "STRING",    doc.get("CPMRN", "")),
            bigquery.ScalarQueryParameter("encounter",        "INT64",     doc.get("encounter", 1)),
            bigquery.ScalarQueryParameter("hospital_name",    "STRING",    doc.get("hospital_name", "")),
            bigquery.ScalarQueryParameter("unit_name",        "STRING",    doc.get("unit_name", "")),
            bigquery.ScalarQueryParameter("urgency",          "STRING",    doc.get("urgency", "")),
            bigquery.ScalarQueryParameter("issues",           "STRING",    doc.get("issues", "")),
            bigquery.ScalarQueryParameter("module",           "STRING",    doc.get("module", "")),
            bigquery.ScalarQueryParameter("create_date_time", "TIMESTAMP", _dt_to_iso(doc.get("create_date_time"))),
            bigquery.ScalarQueryParameter("is_reviewed",      "BOOL",      bool(doc.get("is_reviewed", False))),
            bigquery.ScalarQueryParameter("reviewer_name",    "STRING",    doc.get("reviewer_name", "")),
            bigquery.ScalarQueryParameter("action",           "STRING",    doc.get("action", "")),
            bigquery.ScalarQueryParameter("window_expires_at","TIMESTAMP", _dt_to_iso(doc.get("window_expires_at"))),
            bigquery.ScalarQueryParameter("match_status",     "STRING",    doc.get("match_status", "pending")),
            bigquery.ScalarQueryParameter("synced_at",        "TIMESTAMP", _now_iso()),
        ])
        return n > 0

    def update_sbar(self, sbar_id: str, fields: dict):
        """Update fields on a SBAR row by sbar_id."""
        self._ensure_table("study_sbar_import")
        _update_by_id(self, "study_sbar_import", "sbar_id", sbar_id, fields)

    def find_sbars(self, filter: dict) -> list[dict]:
        self._ensure_table("study_sbar_import")
        clauses, params = _build_where("study_sbar_import", filter)
        where = " AND ".join(clauses) if clauses else "TRUE"
        sql = f"SELECT * FROM {self._fqn('study_sbar_import')} WHERE {where}"
        return self._query(sql, params)

    def count_sbars(self, filter: dict) -> int:
        self._ensure_table("study_sbar_import")
        clauses, params = _build_where("study_sbar_import", filter)
        where = " AND ".join(clauses) if clauses else "TRUE"
        sql = f"SELECT COUNT(*) AS n FROM {self._fqn('study_sbar_import')} WHERE {where}"
        rows = self._query(sql, params)
        return rows[0]["n"] if rows else 0

    # ── study_task_import ─────────────────────────────────────────────────────

    def upsert_task(self, doc: dict) -> bool:
        self._ensure_table("study_task_import")
        sql = f"""
        MERGE {self._fqn("study_task_import")} T
        USING (SELECT @task_id AS task_id) S
        ON T.task_id = S.task_id
        WHEN NOT MATCHED THEN INSERT (
          task_id, CPMRN, encounter, hospital_name, unit_name, title, issues,
          priority, status, task_visible_at, window_expires_at, match_status,
          matched_alert_id, synced_at
        ) VALUES (
          @task_id, @CPMRN, @encounter, @hospital_name, @unit_name, @title, @issues,
          @priority, @status, @task_visible_at, @window_expires_at, @match_status,
          NULL, @synced_at
        )
        """
        n = self._execute(sql, [
            bigquery.ScalarQueryParameter("task_id",          "STRING",    doc["task_id"]),
            bigquery.ScalarQueryParameter("CPMRN",            "STRING",    doc.get("CPMRN", "")),
            bigquery.ScalarQueryParameter("encounter",        "INT64",     doc.get("encounter", 1)),
            bigquery.ScalarQueryParameter("hospital_name",    "STRING",    doc.get("hospital_name", "")),
            bigquery.ScalarQueryParameter("unit_name",        "STRING",    doc.get("unit_name", "")),
            bigquery.ScalarQueryParameter("title",            "STRING",    doc.get("title", "")),
            bigquery.ScalarQueryParameter("issues",           "STRING",    doc.get("issues", "")),
            bigquery.ScalarQueryParameter("priority",         "STRING",    doc.get("priority", "")),
            bigquery.ScalarQueryParameter("status",           "STRING",    doc.get("status", "")),
            bigquery.ScalarQueryParameter("task_visible_at",  "TIMESTAMP", _dt_to_iso(doc.get("task_visible_at"))),
            bigquery.ScalarQueryParameter("window_expires_at","TIMESTAMP", _dt_to_iso(doc.get("window_expires_at"))),
            bigquery.ScalarQueryParameter("match_status",     "STRING",    doc.get("match_status", "pending")),
            bigquery.ScalarQueryParameter("synced_at",        "TIMESTAMP", _now_iso()),
        ])
        return n > 0

    def update_task(self, task_id: str, fields: dict):
        self._ensure_table("study_task_import")
        _update_by_id(self, "study_task_import", "task_id", task_id, fields)

    def find_tasks(self, filter: dict) -> list[dict]:
        self._ensure_table("study_task_import")
        clauses, params = _build_where("study_task_import", filter)
        where = " AND ".join(clauses) if clauses else "TRUE"
        sql = f"SELECT * FROM {self._fqn('study_task_import')} WHERE {where}"
        return self._query(sql, params)

    def count_tasks(self, filter: dict) -> int:
        self._ensure_table("study_task_import")
        clauses, params = _build_where("study_task_import", filter)
        where = " AND ".join(clauses) if clauses else "TRUE"
        sql = f"SELECT COUNT(*) AS n FROM {self._fqn('study_task_import')} WHERE {where}"
        rows = self._query(sql, params)
        return rows[0]["n"] if rows else 0

    # ── append-only tables ────────────────────────────────────────────────────

    def insert_suppressed_event(self, doc: dict):
        self._ensure_table("study_suppressed_events")
        sql = f"""
        INSERT INTO {self._fqn("study_suppressed_events")}
          (CPMRN, encounter, problem_name, suppressed_at, suppression_reason, created_at)
        VALUES
          (@CPMRN, @encounter, @problem_name, @suppressed_at, @suppression_reason, @created_at)
        """
        self._execute(sql, [
            bigquery.ScalarQueryParameter("CPMRN",              "STRING",    doc.get("CPMRN", "")),
            bigquery.ScalarQueryParameter("encounter",          "INT64",     doc.get("encounter", 1)),
            bigquery.ScalarQueryParameter("problem_name",       "STRING",    doc.get("problem_name", "")),
            bigquery.ScalarQueryParameter("suppressed_at",      "TIMESTAMP", _dt_to_iso(doc.get("suppressed_at"))),
            bigquery.ScalarQueryParameter("suppression_reason", "STRING",    doc.get("suppression_reason", "")),
            bigquery.ScalarQueryParameter("created_at",         "TIMESTAMP", _now_iso()),
        ])

    def count_suppressed(self, filter: dict) -> int:
        self._ensure_table("study_suppressed_events")
        clauses, params = _build_where("study_suppressed_events", filter)
        where = " AND ".join(clauses) if clauses else "TRUE"
        sql = f"SELECT COUNT(*) AS n FROM {self._fqn('study_suppressed_events')} WHERE {where}"
        rows = self._query(sql, params)
        return rows[0]["n"] if rows else 0

    def find_suppressed(self, filter: dict) -> list[dict]:
        self._ensure_table("study_suppressed_events")
        clauses, params = _build_where("study_suppressed_events", filter)
        where = " AND ".join(clauses) if clauses else "TRUE"
        sql = f"SELECT * FROM {self._fqn('study_suppressed_events')} WHERE {where}"
        return self._query(sql, params)

    def insert_metrics_snapshot(self, doc: dict):
        self._ensure_table("study_metrics_snapshots")
        # Build columns dynamically — only include fields that have DDL columns
        _METRIC_COLS = {
            "computed_at", "tp", "fp", "fn", "fn_sbar", "fn_task", "tn",
            "total_patient_hours", "sensitivity", "specificity", "ppv", "npv", "f1",
            "sensitivity_ci", "specificity_ci", "ppv_ci",
            "lead_time_median_minutes", "lead_time_iqr_minutes", "lead_time_n",
            "suppressed_total", "suppressed_with_sbar", "pending_adjudication",
            "adj_total", "adj_appropriate", "adj_inappropriate",
            "expl_clear", "expl_partial", "expl_unclear",
            "alerts_total", "sbars_total", "tasks_total",
            "excluded_downtime", "task_excluded_downtime", "task_deduplicated",
        }
        row = {k: v for k, v in doc.items() if k in _METRIC_COLS}
        # CI fields: stored as JSON string
        for ci_col in ("sensitivity_ci", "specificity_ci", "ppv_ci"):
            if ci_col in row and not isinstance(row[ci_col], str):
                row[ci_col] = json.dumps(row[ci_col])
        # computed_at
        if "computed_at" in row:
            row["computed_at"] = _dt_to_iso(row["computed_at"])

        cols = list(row.keys())
        vals = [f"@{c}" for c in cols]
        params = []
        for c in cols:
            v = row[c]
            if c == "computed_at" or c.endswith("_at"):
                params.append(bigquery.ScalarQueryParameter(c, "TIMESTAMP", v))
            elif c in ("sensitivity_ci", "specificity_ci", "ppv_ci"):
                params.append(bigquery.ScalarQueryParameter(c, "STRING", v))
            elif isinstance(v, float) or c in ("sensitivity", "specificity", "ppv", "npv", "f1",
                                                "lead_time_median_minutes", "lead_time_iqr_minutes"):
                params.append(bigquery.ScalarQueryParameter(c, "FLOAT64", float(v) if v is not None else None))
            elif isinstance(v, int) or isinstance(v, type(None)):
                params.append(bigquery.ScalarQueryParameter(c, "INT64", int(v) if v is not None else None))
            else:
                params.append(bigquery.ScalarQueryParameter(c, "STRING", str(v)))

        sql = f"""
        INSERT INTO {self._fqn("study_metrics_snapshots")} ({', '.join(cols)})
        VALUES ({', '.join(vals)})
        """
        self._execute(sql, params)

    def get_latest_metrics_snapshot(self) -> dict | None:
        self._ensure_table("study_metrics_snapshots")
        sql = f"""
        SELECT * FROM {self._fqn("study_metrics_snapshots")}
        ORDER BY computed_at DESC
        LIMIT 1
        """
        rows = self._query(sql)
        return rows[0] if rows else None

    def mark_fp_candidates(self, cutoff_dt: datetime, now: datetime | None = None) -> int:
        """Bulk-mark pending alerts older than cutoff_dt as fp_candidate. Returns row count."""
        self._ensure_table("study_alerts")
        now_iso = _dt_to_iso(now) if now else _now_iso()
        sql = f"""
        UPDATE {self._fqn("study_alerts")}
        SET match_status = 'fp_candidate', fp_candidate_at = @fp_now
        WHERE match_status = 'pending' AND alerted_at < @fp_cutoff
        """
        return self._execute(sql, [
            bigquery.ScalarQueryParameter("fp_cutoff", "TIMESTAMP", _dt_to_iso(cutoff_dt)),
            bigquery.ScalarQueryParameter("fp_now",    "TIMESTAMP", now_iso),
        ])

    def find_matched_alerts_with_sbar(self) -> list[dict]:
        """Return matched/tp_confirmed alerts that have a non-null matched_sbar_id."""
        self._ensure_table("study_alerts")
        sql = f"""
        SELECT alert_id, matched_sbar_id, alerted_at
        FROM {self._fqn("study_alerts")}
        WHERE match_status = 'tp_confirmed'
          AND matched_sbar_id IS NOT NULL
        """
        return self._query(sql)

    def find_adjudications(self) -> list[dict]:
        """Return all adjudication rows."""
        self._ensure_table("study_adjudications")
        sql = f"SELECT * FROM {self._fqn('study_adjudications')}"
        return self._query(sql)

    def insert_run_cost(self, doc: dict):
        self._ensure_table("pipeline_run_costs")
        sql = f"""
        INSERT INTO {self._fqn("pipeline_run_costs")}
          (run_started_at, computed_at, patient_count, trace_count, model, totals, by_step, pricing)
        VALUES
          (@run_started_at, @computed_at, @patient_count, @trace_count, @model, @totals, @by_step, @pricing)
        """
        self._execute(sql, [
            bigquery.ScalarQueryParameter("run_started_at", "TIMESTAMP", _dt_to_iso(doc.get("run_started_at"))),
            bigquery.ScalarQueryParameter("computed_at",    "TIMESTAMP", _dt_to_iso(doc.get("computed_at"))),
            bigquery.ScalarQueryParameter("patient_count",  "INT64",     doc.get("patient_count", 0)),
            bigquery.ScalarQueryParameter("trace_count",    "INT64",     doc.get("trace_count", 0)),
            bigquery.ScalarQueryParameter("model",          "STRING",    doc.get("model", "")),
            bigquery.ScalarQueryParameter("totals",         "STRING",    _to_json_col(doc.get("totals"))),
            bigquery.ScalarQueryParameter("by_step",        "STRING",    _to_json_col(doc.get("by_step"))),
            bigquery.ScalarQueryParameter("pricing",        "STRING",    _to_json_col(doc.get("pricing"))),
        ])


# ── where-clause builder ──────────────────────────────────────────────────────

# Allowed filterable columns per table (prevent SQL injection via column names)
_FILTERABLE: dict[str, set[str]] = {
    "study_alerts":     {"CPMRN", "encounter", "match_status", "alerted_at", "problem_name"},
    "study_sbar_import":{"CPMRN", "encounter", "match_status", "create_date_time", "window_expires_at", "sbar_id"},
    "study_task_import":{"CPMRN", "encounter", "match_status", "task_visible_at", "window_expires_at", "task_id"},
    "study_suppressed_events": {"CPMRN", "encounter", "suppressed_at"},
}


def _build_where(table: str, filter: dict) -> tuple[list[str], list]:
    """Translate a MongoDB-style filter dict to BQ WHERE clauses + parameters."""
    allowed = _FILTERABLE.get(table, set())
    clauses = []
    params  = []
    idx     = 0

    for k, v in filter.items():
        if k not in allowed:
            continue
        pname = f"w_{idx}_{k}"
        idx  += 1

        if isinstance(v, dict):
            for op, operand in v.items():
                op_pname = f"{pname}_{op.lstrip('$')}"
                p_type, py_val = _infer_type(operand)
                if op == "$gte":
                    clauses.append(f"{k} >= @{op_pname}")
                elif op == "$lte":
                    clauses.append(f"{k} <= @{op_pname}")
                elif op == "$lt":
                    clauses.append(f"{k} < @{op_pname}")
                elif op == "$gt":
                    clauses.append(f"{k} > @{op_pname}")
                elif op == "$in":
                    # Use UNNEST for $in
                    arr_pname = f"{op_pname}_arr"
                    clauses.append(f"{k} IN UNNEST(@{arr_pname})")
                    params.append(bigquery.ArrayQueryParameter(arr_pname, "STRING", [str(x) for x in operand]))
                    continue
                elif op == "$ne":
                    clauses.append(f"({k} IS NULL OR {k} != @{op_pname})")
                params.append(bigquery.ScalarQueryParameter(op_pname, p_type, py_val))
        elif isinstance(v, list):
            clauses.append(f"{k} IN UNNEST(@{pname})")
            params.append(bigquery.ArrayQueryParameter(pname, "STRING", [str(x) for x in v]))
        else:
            p_type, py_val = _infer_type(v)
            clauses.append(f"{k} = @{pname}")
            params.append(bigquery.ScalarQueryParameter(pname, p_type, py_val))

    return clauses, params


def _infer_type(v) -> tuple[str, Any]:
    if isinstance(v, bool):
        return "BOOL", v
    if isinstance(v, int):
        return "INT64", v
    if isinstance(v, float):
        return "FLOAT64", v
    if isinstance(v, datetime):
        return "TIMESTAMP", _dt_to_iso(v)
    return "STRING", str(v) if v is not None else None


def _update_by_id(store: BQStudyStore, table: str, id_col: str, id_val: str, fields: dict):
    """Generic UPDATE by primary key."""
    if not fields:
        return
    set_parts = []
    params    = [bigquery.ScalarQueryParameter("_pk", "STRING", id_val)]
    for k, v in fields.items():
        pname = f"u_{k}"
        p_type, py_val = _infer_type(v)
        set_parts.append(f"{k} = @{pname}")
        params.append(bigquery.ScalarQueryParameter(pname, p_type, py_val))
    sql = f"""
    UPDATE {store._fqn(table)}
    SET {', '.join(set_parts)}
    WHERE {id_col} = @_pk
    """
    store._execute(sql, params)


# ── Factory ───────────────────────────────────────────────────────────────────

_store_instance: BQStudyStore | None = None


def get_bq_store() -> BQStudyStore:
    global _store_instance
    if _store_instance is None:
        _store_instance = BQStudyStore(
            project=os.environ.get("BQ_PROJECT", _PROJECT),
            dataset=os.environ.get("BQ_DATASET", _DATASET),
        )
    return _store_instance
